### ISSUE TITLE
KDSoapJob finished(...) signal not fired for response

### ISSUE THREAD

**Issue by cjh1** [KDAB/KDSoap#94] opened 2016-12-07 20:39 UTC
Since upgraded to the latest version (1.5.1) from 1.3 we have stop receiving the finished(...) signal for one of our responses. Using KDSOAP_DEBUG we see the response come from the server:

"<?xml version=\"1.0\" encoding=\"utf-8\"?><soapenv:Envelope xmlns:soapenv=\"htt
p://schemas.xmlsoap.org/soap/envelope/\" xmlns:xsd=\"http://www.w3.org/2001/XMLS
chema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"><soapenv:Body><n
s1:createDirectoryResponse soapenv:encodingStyle=\"http://schemas.xmlsoap.org/so
ap/encoding/\" xmlns:ns1=\"https://www.uit.hpc.mil/UITAPIv3/uitapi.jws\"/></soap
env:Body></soapenv:Envelope>"

The WSDL we used to create the being with can be seen here:

https://www.uit.hpc.mil/UITAPIv3/uitapi.jws?wsdl

**Comment by cjh1** [comment] 2016-12-07 20:40
@cryos

**Comment by cjh1** [comment] 2016-12-14 18:48
So I think the problem is [here](https://github.com/KDAB/KDSoap/blob/master/kdwsdl2cpp/src/converter_clientstub.cpp#L390-L396)

```cpp
                    // Protect the call to .at(0) below
                    slotCode += "if (_reply.childValues().isEmpty()) {";
                    slotCode.indent();
                    slotCode += "_reply.setFault(true);" + COMMENT;
                    slotCode += "_reply.addArgument(QString::fromLatin1(\"faultcode\"), QString::fromLatin1(\"Server.EmptyResponse\"));";
                    slotCode += QLatin1String("return;");
                    slotCode.unindent();
                    slotCode += "}";
```

For responses that don't have any values returned this generates code that willl not fire the finished(...) signal. Not sure why have a response with no values is being tagged as an error either. There generated code is as follows

```cpp
    watcher->deleteLater();
    KDSoapMessage _reply = watcher->returnMessage();
    if (!_reply.isFault()) {// converter_clientstub.cpp:387
        if (_reply.childValues().isEmpty()) {
            _reply.setFault(true);// converter_clientstub.cpp:394
            _reply.addArgument(QString::fromLatin1("faultcode"), QString::fromLatin1("Server.EmptyResponse"));
            return;
        }
        _reply = _reply.childValues().at(0);// converter_clientstub.cpp:400
    }
    emitFinished(_reply, watcher->returnHeaders());
```

My proposal would be to remove hold block that tags this as an error. I don't see why this is a error?

**Comment by dfaure-kdab** [comment] 2016-12-14 20:53
Well, if a reply is expected and none is present, then it's an error. If you just remove the if() block, then this code will be calling at(0) on an empty list, which will assert in debug mode.

But you're right, the problem is that the early return skips the emitFinished call.
This code should use else instead of return like
```cpp
    KDSoapMessage _reply = watcher->returnMessage();
    if (!_reply.isFault()) {// converter_clientstub.cpp:387
        if (_reply.childValues().isEmpty()) {
            _reply.setFault(true);// converter_clientstub.cpp:394
            _reply.addArgument(QString::fromLatin1("faultcode"), QString::fromLatin1("Server.EmptyResponse"));
        } else {
            _reply = _reply.childValues().at(0);// converter_clientstub.cpp:400
        }
    }
    emitFinished(_reply, watcher->returnHeaders());
```

What do you think? Does this make sense to you?
The question of why you're getting empty responses remains though.

**Comment by cjh1** [comment] 2016-12-14 21:02
> Well, if a reply is expected and none is present, then it's an error. If you just remove the if() block, then this code will be calling at(0) on an empty list, which will assert in debug mode.

This would be the patch I was proposing:

https://github.com/cjh1/KDSoap/commit/47bbf34aa77f210b7422924afa7e71ef62f5b516

Only try to extract a return value if there is one. 

> What do you think? Does this make sense to you?
> The question of why you're getting empty responses remains though.

Its an empty response because that is what is defined in the WSDL and is what the server returns. My understanding is there is nothing requiring a return value. Here is the snippet of WDSL for the response:

```XML
<wsdl:message name="createDirectoryResponse"></wsdl:message>
```

**Comment by dfaure-kdab** [comment] 2016-12-14 21:03
BTW I can't access the WSDL file, the error is: unable to resolve host address ‘www.uit.hpc.mil’

Can you send me the wsdl file? (first name dot last name at kdab.com)

Heh I just noticed that you work for kitware; small world (big cmake fan here).

**Comment by dfaure-kdab** [comment] 2016-12-14 21:06
Ah I see what you mean. Well this would silently ignore the case where a reply was expected and none was provided. I think we can do better, the code generator knows whether a reply is expected or not, for this particular code. I'll dig in a bit, to suggest something better.
In any case, a unit test would be useful too (which is why I was trying to get hold of the WSDL file, otherwise we can play with another of the RPC-mode unittests).

**Comment by cjh1** [comment] 2016-12-14 21:07
I will attach the WSDL ( glad you like CMake :smile:  )

**Comment by dfaure-kdab** [comment] 2016-12-14 21:09
I think the fix could be
```cpp
-                if (soapStyle(binding) == SoapBinding::RPCStyle /*adds a wrapper*/) {
+                if (soapStyle(binding) == SoapBinding::RPCStyle /*adds a wrapper*/ && !message.parts().isEmpty()) {
```

**Comment by cjh1** [comment] 2016-12-14 21:10
[uitapi.txt](https://github.com/KDAB/KDSoap/files/652863/uitapi.txt)

**Comment by cjh1** [comment] 2016-12-14 21:10
Yes, that looks better

**Comment by cjh1** [comment] 2016-12-14 21:19
Will you push a PR or would you like me to?

**Comment by dfaure-kdab** [comment] 2016-12-14 21:20
I'm looking into writing a unittest first.

**Comment by dfaure-kdab** [comment] 2016-12-14 21:32
Unittest good. Unittest shows fix not good ;) Investigating.

**Comment by dfaure-kdab** [comment] 2016-12-14 21:45
Fixed in fb44069, thanks for the report, the investigation and the testcase.

**Closed by dfaure-kdab** 2016-12-14 21:45 UTC

**Comment by cjh1** [comment] 2016-12-14 21:47
Awesome! Thanks for the quick fix!

**Comment by cryos** [comment] 2016-12-14 21:48
Great to see this resolved so quickly, we can test it out in the live system tomorrow.
