### ISSUE TITLE
1.9.0 release - LICENSE.US.txt file missing

### ISSUE THREAD

**Issue by manuelh** [KDAB/KDSoap#208] opened 2020-03-02 11:21 UTC
Trying to run configure on Windows and get the following error:

'license' is not recognized as an internal or external command,
operable program or batch file.

In my case it is hitting the else branch of line 33 of configure.bat:
if exist %SOURCE_DIR%\LICENSE.US.txt (

The LICENSE.US.txt file is missing.

**Comment by winterz** [comment] 2020-03-02 21:46
I don't get it.
'if exist %SOURCE_DIR%\LICENSE.US.txt'  should fail and all should be fine.

LICENSE.US.txt has been removed on purpose.

**Comment by anoymouserver** [comment] 2020-03-09 15:39
It seems like there's a space in the path.
Try to qoute the paths like so:
`if exist "%SOURCE_DIR%\LICENSE.US.txt" (`

**Comment by winterz** [comment] 2020-03-09 16:14
makes sense. I'll see if I can fix sometime soon.
you could remove whitespace from your source_dir in the meantime.

**Comment by anoymouserver** [comment] 2020-03-10 08:09
I've debugged it a little further..
The issue is that the license selection is only displayed if all three license files exist.
https://github.com/KDAB/KDSoap/blob/13e459cce89b72c5ec9986a3a1646040ea8371ff/autogen/configure.bat.in#L36
The mentioned error output happens since Windows needs a `set` before a variable. (e.g. `set license=1`)
https://github.com/KDAB/KDSoap/blob/13e459cce89b72c5ec9986a3a1646040ea8371ff/autogen/configure.bat.in#L46 (also line 50 and 53)
These else blocks were previously never reached since all files existed.
I could create a PR with these changes, but the lic selection would still never be displayed.

Nevertheless it would be good to insert the quotes to avoid problems with spaces.

**Comment by winterz** [comment] 2020-04-10 14:39
hopefully fixed in 8f88268b4e813ea9734f0363f6ecf9218cac428e
would appreciate more testing as I don't use Windows very often.

**Closed by winterz** 2020-04-10 14:39 UTC
